### ISSUE TITLE
Random white texture issue 

### ISSUE THREAD

**Issue by gta191977649** [Wolfee-J/MTA-Stream#1]
Hello, I've upgraded the Jstreamer to MTA-Stream, after I upgrade to MTA-Stream, I found some parts of my map model's texture are incorrect and white, each time I restart the game, the white texture occurred randomly on different models. there is no problem when I using Jstreamer before.

My Map:
![TIM截图20200712030741](https://user-images.githubusercontent.com/2988235/87229767-5c83dd80-c3ee-11ea-87a8-65549808117e.png)
![TIM截图20200712030758](https://user-images.githubusercontent.com/2988235/87229768-5e4da100-c3ee-11ea-97b7-25f77d113e27.png)

White Texture also exists in the MTA-Vice-City resource:
![TIM截图20200712030335](https://user-images.githubusercontent.com/2988235/87229770-61489180-c3ee-11ea-898e-df8ebb8e9f93.png)

Please help! 
Thanks

**Comment by Wolfee-J** [comment]
Thank you for the report, currently investigating this issue, may you please send me your clientscript.log?
Typically located at C:\Program Files (x86)\MTA San Andreas 1.5\MTA\logs, however it may differ depending on your MTA installation location.

**Comment by gta191977649** [comment]
Sure!
**clientscript.log:** -> [clientscript.log](https://github.com/Wolfee-J/MTA-Stream/files/4907454/clientscript.log)
**console.log** -> [console.log](https://github.com/Wolfee-J/MTA-Stream/files/4907459/console.log)
**logfile.txt** -> [logfile.txt](https://github.com/Wolfee-J/MTA-Stream/files/4907461/logfile.txt)
![TIM截图20200712043747](https://user-images.githubusercontent.com/2988235/87231328-a625f580-c3f9-11ea-8c43-2ecb9bd26d66.png)
![TIM截图20200712043824](https://user-images.githubusercontent.com/2988235/87231329-a7efb900-c3f9-11ea-934d-c6217ead959b.png)

**Comment by Wolfee-J** [comment]
Thank you, doesn't seem to have any relevant information however I will see what I can do.

**Comment by Wolfee-J** [comment]
What are your computer specs?

**Comment by gta191977649** [comment]
> What are your computer specs?

Intel Core i7-7740X 4.3 GHz
NVIDIA GeForce GTX 1080 Ti11 GB VRAM
32 GB RAM
Windows 10

**Comment by gta191977649** [comment]
well, the problem is gone after I cleaned all the files in my MTA client resources folder. so it's my bad lol. so everything works like a charm :)

**Comment by Wolfee-J** [comment]
Oh alright, thank you for the report anyways. I'll describe this as a possible fix.
