### ISSUE TITLE
Flying Foliage

### ISSUE THREAD

**Issue by turret001** [Wolfee-J/MTA-Stream#6]
![image](https://user-images.githubusercontent.com/24281147/86281239-ead5b380-bbe5-11ea-904b-d902d49f3dbc.png)

Using latest version on MTA-Stream. This is from Vice City map. I wasn't sure if this issue is caused by MTA-Stream or VC but I think it's MTA Stream. 
pos: 470.86511, -549.33722, 36.78971

**Comment by Wolfee-J** [comment]
Cannot reproduce.
